// Mock Issues Data — RIRRS
// Locations centered around various Indian cities

const MOCK_ISSUES = [
  {
    id: 'ISS-001',
    title: 'Large pothole on MG Road near City Mall',
    description: 'A large pothole has formed on MG Road near the City Mall junction. It is approximately 2 feet wide and 8 inches deep. Multiple vehicles have been damaged. The pothole fills with water during rain making it invisible to drivers.',
    category: 'POTHOLE',
    status: 'PENDING',
    priority: 'HIGH',
    latitude: 23.0225,
    longitude: 72.5714,
    address: 'MG Road, Near City Mall, Ahmedabad',
    ward: 'Ward 12',
    upvoteCount: 24,
    slaDeadline: '2026-04-02T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-25T10:30:00Z',
    updatedAt: '2026-03-28T14:20:00Z',
    reporterId: 'usr_citizen_001',
    reporterName: 'Rahul Sharma',
    assigneeId: null,
    assigneeName: null,
    photos: [
      { id: 'ph_001', url: '/images/pothole.png', type: 'report' },
      { id: 'ph_002', url: '/images/pothole.png', type: 'report' },
    ],
    comments: [
      { id: 'cmt_001', userId: 'usr_citizen_001', userName: 'Rahul Sharma', body: 'This pothole has been here for over 2 weeks now.', isInternal: false, createdAt: '2026-03-25T10:35:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'ISS-002',
    title: 'Broken streetlight at Satellite Road junction',
    description: 'The streetlight at the main junction of Satellite Road has been broken for 5 days. The area becomes very dark at night causing safety concerns for pedestrians and especially women.',
    category: 'STREETLIGHT',
    status: 'UNDER_REVIEW',
    priority: 'MEDIUM',
    latitude: 23.0275,
    longitude: 72.5290,
    address: 'Satellite Road Junction, Ahmedabad',
    ward: 'Ward 8',
    upvoteCount: 12,
    slaDeadline: '2026-04-05T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-24T18:00:00Z',
    updatedAt: '2026-03-27T09:15:00Z',
    reporterId: 'usr_citizen_002',
    reporterName: 'Neha Desai',
    assigneeId: null,
    assigneeName: null,
    photos: [
      { id: 'ph_003', url: '/images/streetlight.png', type: 'report' },
    ],
    comments: [],
    feedback: null,
  },
  {
    id: 'ISS-003',
    title: 'Clogged drain causing waterlogging near SG Highway',
    description: 'Major drain near SG Highway service road is completely clogged with debris and plastic waste. During even light rain, the entire road gets waterlogged up to knee level, making it impassable.',
    category: 'DRAIN',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    latitude: 23.0469,
    longitude: 72.5273,
    address: 'SG Highway Service Road, Near Iskcon Temple, Ahmedabad',
    ward: 'Ward 15',
    upvoteCount: 45,
    slaDeadline: '2026-03-31T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-20T08:00:00Z',
    updatedAt: '2026-03-29T16:00:00Z',
    reporterId: 'usr_citizen_003',
    reporterName: 'Vijay Mehta',
    assigneeId: 'usr_field_001',
    assigneeName: 'Amit Kumar',
    photos: [
      { id: 'ph_004', url: '/images/rubble.png', type: 'report' },
      { id: 'ph_005', url: '/images/rubble.png', type: 'before' },
    ],
    comments: [
      { id: 'cmt_002', userId: 'usr_field_001', userName: 'Amit Kumar', body: 'Reached site. The drain is severely blocked. Will need heavy equipment.', isInternal: false, createdAt: '2026-03-29T10:00:00Z' },
      { id: 'cmt_003', userId: 'usr_admin_001', userName: 'Priya Patel', body: 'Equipment dispatched. ETA 2 hours.', isInternal: true, createdAt: '2026-03-29T10:30:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'ISS-004',
    title: 'Road crack spreading on Law Garden road',
    description: 'A crack in the road surface has been spreading over the past month. It now stretches about 15 meters along the road. The crack is deep enough to cause damage to two-wheelers.',
    category: 'ROAD_CRACK',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    latitude: 23.0300,
    longitude: 72.5600,
    address: 'Law Garden Road, Ahmedabad',
    ward: 'Ward 10',
    upvoteCount: 8,
    slaDeadline: '2026-03-28T00:00:00Z',
    resolvedAt: '2026-03-27T14:00:00Z',
    closedAt: null,
    createdAt: '2026-03-18T12:00:00Z',
    updatedAt: '2026-03-27T14:00:00Z',
    reporterId: 'usr_citizen_004',
    reporterName: 'Kavita Shah',
    assigneeId: 'usr_field_002',
    assigneeName: 'Ramesh Prajapati',
    photos: [
      { id: 'ph_006', url: '/images/pothole.png', type: 'report' },
      { id: 'ph_007', url: '/images/rubble.png', type: 'before' },
      { id: 'ph_008', url: '/images/rubble.png', type: 'after' },
    ],
    comments: [
      { id: 'cmt_004', userId: 'usr_field_002', userName: 'Ramesh Prajapati', body: 'Road surface repaired and smoothened. Applied fresh tar coating.', isInternal: false, createdAt: '2026-03-27T14:00:00Z' },
    ],
    feedback: { rating: 4, comment: 'Good repair but took too long.', createdAt: '2026-03-28T10:00:00Z' },
  },
  {
    id: 'ISS-005',
    title: 'Missing road signage at Vastrapur Lake circle',
    description: 'The speed limit sign and the stop sign at Vastrapur Lake circle have been missing since the recent construction work. This is causing confusion among drivers.',
    category: 'SIGNAGE',
    status: 'CLOSED',
    priority: 'LOW',
    latitude: 23.0380,
    longitude: 72.5290,
    address: 'Vastrapur Lake Circle, Ahmedabad',
    ward: 'Ward 7',
    upvoteCount: 6,
    slaDeadline: '2026-04-01T00:00:00Z',
    resolvedAt: '2026-03-26T10:00:00Z',
    closedAt: '2026-03-27T09:00:00Z',
    createdAt: '2026-03-19T15:00:00Z',
    updatedAt: '2026-03-27T09:00:00Z',
    reporterId: 'usr_citizen_001',
    reporterName: 'Rahul Sharma',
    assigneeId: 'usr_field_001',
    assigneeName: 'Amit Kumar',
    photos: [
      { id: 'ph_009', url: '/images/streetlight.png', type: 'report' },
      { id: 'ph_010', url: '/images/streetlight.png', type: 'after' },
    ],
    comments: [],
    feedback: { rating: 5, comment: 'New signs look great! Thank you.', createdAt: '2026-03-27T12:00:00Z' },
  },
  {
    id: 'ISS-006',
    title: 'Deep pothole near Manek Chowk',
    description: 'Very deep pothole has formed near Manek Chowk market entrance. Multiple bikes have fallen here. Needs urgent attention.',
    category: 'POTHOLE',
    status: 'PENDING',
    priority: 'CRITICAL',
    latitude: 23.0258,
    longitude: 72.5873,
    address: 'Manek Chowk, Old City, Ahmedabad',
    ward: 'Ward 3',
    upvoteCount: 32,
    slaDeadline: '2026-03-31T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-28T07:00:00Z',
    updatedAt: '2026-03-28T07:00:00Z',
    reporterId: 'usr_citizen_005',
    reporterName: 'Mohammad Ali',
    assigneeId: null,
    assigneeName: null,
    photos: [
      { id: 'ph_011', url: '/images/pothole.png', type: 'report' },
    ],
    comments: [],
    feedback: null,
  },
  {
    id: 'ISS-007',
    title: 'Multiple streetlights out on CG Road',
    description: 'At least 5 consecutive streetlights are out on CG Road between Swastik Cross Roads and Navrangpura junction. Very dangerous at night.',
    category: 'STREETLIGHT',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    latitude: 23.0350,
    longitude: 72.5600,
    address: 'CG Road, Navrangpura, Ahmedabad',
    ward: 'Ward 11',
    upvoteCount: 18,
    slaDeadline: '2026-04-01T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-22T20:00:00Z',
    updatedAt: '2026-03-28T11:00:00Z',
    reporterId: 'usr_citizen_002',
    reporterName: 'Neha Desai',
    assigneeId: 'usr_field_003',
    assigneeName: 'Suresh Vaghela',
    photos: [
      { id: 'ph_012', url: '/images/streetlight.png', type: 'report' },
    ],
    comments: [],
    feedback: null,
  },
  {
    id: 'ISS-008',
    title: 'Manhole cover missing on Ashram Road',
    description: 'DANGER: A manhole cover is completely missing on Ashram Road near Paldi junction. This is an extreme safety hazard. Someone fell in yesterday.',
    category: 'OTHER',
    status: 'UNDER_REVIEW',
    priority: 'CRITICAL',
    latitude: 23.0175,
    longitude: 72.5700,
    address: 'Ashram Road, Paldi, Ahmedabad',
    ward: 'Ward 5',
    upvoteCount: 56,
    slaDeadline: '2026-03-30T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-29T06:00:00Z',
    updatedAt: '2026-03-29T08:00:00Z',
    reporterId: 'usr_citizen_006',
    reporterName: 'Anita Joshi',
    assigneeId: null,
    assigneeName: null,
    photos: [
      { id: 'ph_013', url: '/images/pothole.png', type: 'report' },
    ],
    comments: [
      { id: 'cmt_005', userId: 'usr_citizen_006', userName: 'Anita Joshi', body: 'Please fix this urgently! Kids play near here.', isInternal: false, createdAt: '2026-03-29T06:05:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'ISS-009',
    title: 'Road surface breaking near BRTS stop',
    description: 'The road near the Gurukul BRTS stop is breaking apart. Large chunks of asphalt are missing. Affects both sides of the road.',
    category: 'ROAD_CRACK',
    status: 'PENDING',
    priority: 'MEDIUM',
    latitude: 23.0400,
    longitude: 72.5450,
    address: 'Near Gurukul BRTS Stop, Ahmedabad',
    ward: 'Ward 9',
    upvoteCount: 14,
    slaDeadline: '2026-04-06T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-26T09:00:00Z',
    updatedAt: '2026-03-26T09:00:00Z',
    reporterId: 'usr_citizen_003',
    reporterName: 'Vijay Mehta',
    assigneeId: null,
    assigneeName: null,
    photos: [
      { id: 'ph_014', url: '/images/pothole.png', type: 'report' },
    ],
    comments: [],
    feedback: null,
  },
  {
    id: 'ISS-010',
    title: 'Drain overflow on Relief Road',
    description: 'The drain on Relief Road near Fernandes Bridge is overflowing with sewage. Very unhygienic conditions. Bad smell making it difficult for shopkeepers.',
    category: 'DRAIN',
    status: 'RESOLVED',
    priority: 'HIGH',
    latitude: 23.0230,
    longitude: 72.5850,
    address: 'Relief Road, Near Fernandes Bridge, Ahmedabad',
    ward: 'Ward 4',
    upvoteCount: 22,
    slaDeadline: '2026-03-28T00:00:00Z',
    resolvedAt: '2026-03-27T16:00:00Z',
    closedAt: null,
    createdAt: '2026-03-21T11:00:00Z',
    updatedAt: '2026-03-27T16:00:00Z',
    reporterId: 'usr_citizen_007',
    reporterName: 'Firoz Khan',
    assigneeId: 'usr_field_002',
    assigneeName: 'Ramesh Prajapati',
    photos: [
      { id: 'ph_015', url: '/images/rubble.png', type: 'report' },
      { id: 'ph_016', url: '/images/rubble.png', type: 'after' },
    ],
    comments: [],
    feedback: { rating: 3, comment: 'Fixed but took over a week. Could be faster.', createdAt: '2026-03-28T10:00:00Z' },
  },
  {
    id: 'ISS-011',
    title: 'Pothole cluster on Sarkhej-Gandhinagar Highway',
    description: 'A series of potholes has formed on the highway stretch near the GIFT City exit. Very dangerous for high-speed traffic.',
    category: 'POTHOLE',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    latitude: 23.1050,
    longitude: 72.5800,
    address: 'Sarkhej-Gandhinagar Highway, Near GIFT City, Ahmedabad',
    ward: 'Ward 20',
    upvoteCount: 38,
    slaDeadline: '2026-04-01T00:00:00Z',
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-23T14:00:00Z',
    updatedAt: '2026-03-29T09:00:00Z',
    reporterId: 'usr_citizen_008',
    reporterName: 'Dhruv Thakkar',
    assigneeId: 'usr_field_001',
    assigneeName: 'Amit Kumar',
    photos: [
      { id: 'ph_017', url: '/images/pothole.png', type: 'report' },
    ],
    comments: [
      { id: 'cmt_006', userId: 'usr_field_001', userName: 'Amit Kumar', body: 'Identified 4 potholes. Filling work started.', isInternal: false, createdAt: '2026-03-29T09:00:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'ISS-012',
    title: 'Faded zebra crossing at school zone',
    description: 'The zebra crossing markings near Delhi Public School on Drive In Road have completely faded. Children crossing here every day are at risk.',
    category: 'SIGNAGE',
    status: 'PENDING',
    priority: 'HIGH',
    latitude: 23.0450,
    longitude: 72.5350,
    address: 'Drive In Road, Near DPS School, Ahmedabad',
    ward: 'Ward 14',
    upvoteCount: 28,
    slaDeadline: null,
    resolvedAt: null,
    closedAt: null,
    createdAt: '2026-03-27T08:00:00Z',
    updatedAt: '2026-03-27T08:00:00Z',
    reporterId: 'usr_citizen_009',
    reporterName: 'Sunita Rawat',
    assigneeId: null,
    assigneeName: null,
    photos: [
      { id: 'ph_018', url: '/images/streetlight.png', type: 'report' },
    ],
    comments: [],
    feedback: null,
  },
];

// Field Workers
const MOCK_FIELD_WORKERS = [
  {
    id: 'usr_field_001',
    name: 'Amit Kumar',
    email: 'fieldworker@rirrs.in',
    phone: '+91 98765 22222',
    role: 'field',
    specialization: 'Road Repair',
    assignedTasks: 2,
    completedTasks: 15,
    rating: 4.2,
    isActive: true,
    ward: 'Ward 15',
  },
  {
    id: 'usr_field_002',
    name: 'Ramesh Prajapati',
    email: 'ramesh@rirrs.in',
    phone: '+91 98765 33333',
    role: 'field',
    specialization: 'Drainage',
    assignedTasks: 1,
    completedTasks: 22,
    rating: 4.5,
    isActive: true,
    ward: 'Ward 10',
  },
  {
    id: 'usr_field_003',
    name: 'Suresh Vaghela',
    email: 'suresh@rirrs.in',
    phone: '+91 98765 44444',
    role: 'field',
    specialization: 'Electrical',
    assignedTasks: 1,
    completedTasks: 18,
    rating: 4.0,
    isActive: true,
    ward: 'Ward 11',
  },
  {
    id: 'usr_field_004',
    name: 'Prakash Solanki',
    email: 'prakash@rirrs.in',
    phone: '+91 98765 55555',
    role: 'field',
    specialization: 'Road Repair',
    assignedTasks: 0,
    completedTasks: 10,
    rating: 3.8,
    isActive: false,
    ward: 'Ward 7',
  },
];

// Notifications
const MOCK_NOTIFICATIONS = [
  {
    id: 'notif_001',
    type: 'STATUS_UPDATE',
    message: 'Your report "Large pothole on MG Road" is now being reviewed.',
    issueId: 'ISS-001',
    isRead: false,
    createdAt: '2026-03-29T14:00:00Z',
  },
  {
    id: 'notif_002',
    type: 'RESOLUTION',
    message: 'Great news! "Road crack on Law Garden road" has been resolved. Please rate the resolution.',
    issueId: 'ISS-004',
    isRead: false,
    createdAt: '2026-03-27T14:00:00Z',
  },
  {
    id: 'notif_003',
    type: 'ASSIGNMENT',
    message: 'You have been assigned a new task: "Clogged drain near SG Highway".',
    issueId: 'ISS-003',
    isRead: true,
    createdAt: '2026-03-26T09:00:00Z',
  },
  {
    id: 'notif_004',
    type: 'SLA_BREACH',
    message: 'Issue "Deep pothole near Manek Chowk" is approaching its SLA deadline (24h remaining).',
    issueId: 'ISS-006',
    isRead: false,
    createdAt: '2026-03-30T06:00:00Z',
  },
  {
    id: 'notif_005',
    type: 'STATUS_UPDATE',
    message: 'Work has started on "Missing road signage at Vastrapur Lake".',
    issueId: 'ISS-005',
    isRead: true,
    createdAt: '2026-03-24T10:00:00Z',
  },
];

// Analytics
const MOCK_ANALYTICS = {
  summary: {
    totalIssues: 248,
    openIssues: 84,
    resolvedIssues: 142,
    closedIssues: 22,
    avgResolutionDays: 5.2,
    satisfactionScore: 4.1,
    slaCompliance: 87,
    activeWorkers: 12,
  },
  byCategory: [
    { name: 'Pothole', count: 82, percentage: 33 },
    { name: 'Streetlight', count: 45, percentage: 18 },
    { name: 'Drain', count: 38, percentage: 15 },
    { name: 'Road Crack', count: 35, percentage: 14 },
    { name: 'Signage', count: 28, percentage: 11 },
    { name: 'Other', count: 20, percentage: 8 },
  ],
  byStatus: [
    { name: 'Pending', count: 42, color: '#B56A10' },
    { name: 'Under Review', count: 22, color: '#1E4DB7' },
    { name: 'In Progress', count: 20, color: '#6C8AFF' },
    { name: 'Resolved', count: 142, color: '#1A7A4A' },
    { name: 'Closed', count: 22, color: '#8A8A84' },
  ],
  byWard: [
    { ward: 'Ward 3', count: 28 },
    { ward: 'Ward 5', count: 22 },
    { ward: 'Ward 7', count: 18 },
    { ward: 'Ward 8', count: 15 },
    { ward: 'Ward 10', count: 20 },
    { ward: 'Ward 11', count: 25 },
    { ward: 'Ward 12', count: 30 },
    { ward: 'Ward 14', count: 12 },
    { ward: 'Ward 15', count: 35 },
    { ward: 'Ward 20', count: 15 },
  ],
  resolutionTrend: [
    { month: 'Oct', avgDays: 7.2, issues: 28 },
    { month: 'Nov', avgDays: 6.8, issues: 35 },
    { month: 'Dec', avgDays: 6.1, issues: 30 },
    { month: 'Jan', avgDays: 5.8, issues: 42 },
    { month: 'Feb', avgDays: 5.5, issues: 38 },
    { month: 'Mar', avgDays: 5.2, issues: 45 },
  ],
  monthlySubmissions: [
    { month: 'Oct', submitted: 28, resolved: 22 },
    { month: 'Nov', submitted: 35, resolved: 28 },
    { month: 'Dec', submitted: 30, resolved: 25 },
    { month: 'Jan', submitted: 42, resolved: 35 },
    { month: 'Feb', submitted: 38, resolved: 32 },
    { month: 'Mar', submitted: 45, resolved: 38 },
  ],
};

export { MOCK_ISSUES, MOCK_FIELD_WORKERS, MOCK_NOTIFICATIONS, MOCK_ANALYTICS };
